version: "3"
services:
  api:
    container_name: playr_api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    command: "npm start"
    env_file:
      - ./api/.env
    environment:
    - NODE_ENV=production
    - DB_HOST=playr_postgres
    - LOG_PATH=/var/log/
  postgres:
    container_name: playr_postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "playr"
